export const GET_CART_PRODUCT_REQUEST = "GET_CART_PRODUCT_REQUEST";
export const GET_CART_PRODUCT_SUCCESS = "GET_CART_PRODUCT_SUCCESS";
export const GET_CART_PRODUCT_ERROR = "GET_CART_PRODUCT_ERROR";

export const POST_CART_PRODUCT_REQUEST = "POST_CART_PRODUCT_REQUEST";
export const POST_CART_PRODUCT_SUCCESS = "POST_CART_PRODUCT_SUCCESS";
export const POST_CART_PRODUCT_ERROR = "POST_CART_PRODUCT_ERROR";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const DELETE_CART_PRODUCT_REQUEST = "DELETE_CART_PRODUCT_REQUEST";
export const DELETE_CART_PRODUCT_SUCCESS = "DELETE_CART_PRODUCT_SUCCESS";
export const DELETE_CART_PRODUCT_ERROR = "DELETE_CART_PRODUCT_ERROR";

export const UPDATE_QUANTITY_REQUEST = "UPDATE_QUANTITY_REQUEST";
export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const UPDATE_QUANTITY_ERROR = "UPDATE_QUANTITY_ERROR";

export const GET_TOTALMRP_REQUEST = "GET_TOTALMRP_REQUEST";
export const GET_TOTALMRP_SUCCESS = "GET_TOTALMRP_SUCCESS";
export const GET_TOTALMRP_ERROR = "GET_TOTALMRP_ERROR";

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_ERROR = "GET_DISCOUNT_ERROR";

export const TOTALMRP="TOTALMRP";
export const TOTALPRICE="TOTALPRICE"

