export const GET_MEN_PRODUCT_REQUEST = "GET_MEN_PRODUCT_REQUEST";
export const GET_MEN_PRODUCT_SUCCESS = "GET_MEN_PRODUCT_SUCCESS";
export const GET_MEN_PRODUCT_ERROR = "GET_MEN_PRODUCT_ERROR";

export const GET_WOMEN_PRODUCT_REQUEST = "GET_WOMEN_PRODUCT_REQUEST";
export const GET_WOMEN_PRODUCT_SUCCESS = "GET_WOMEN_PRODUCT_SUCCESS";
export const GET_WOMEN_PRODUCT_ERROR = "GET_WOMEN_PRODUCT_ERROR";
