export const GET_CART_PRODUCT_REQUEST = "GET_CART_PRODUCT_REQUEST";
export const GET_CART_PRODUCT_SUCCESS = "GET_CART_PRODUCT_SUCCESS";
export const GET_CART_PRODUCT_ERROR = "GET_CART_PRODUCT_ERROR";

export const POST_CART_PRODUCT_REQUEST = "POST_CART_PRODUCT_REQUEST";
export const POST_CART_PRODUCT_SUCCESS = "POST_CART_PRODUCT_SUCCESS";
export const POST_CART_PRODUCT_ERROR = "POST_CART_PRODUCT_ERROR";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";