export const  PAYMENT_REQUEST="PAYMENT_REQUEST";
export const PAYMENT_SUCCESS="PAYMENT_SUCCESS";
export const PAYMENT_FAILURE="PAYMENT_FAILURE";

//AFTER PAYMENT SUCCESSFULL CLEAR CART
export const CLEAR_CART="CLEAR_CART"